# Generated by Django 3.1.2 on 2020-10-29 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('Web-Developer', 'Web-Developer'), ('Maintainer', 'Maintainer'), ('Mentor', 'Mentor')], max_length=20)),
                ('profile_image', models.ImageField(default='default.png', upload_to='member_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
